project:
  type: book
  output-dir: docs

book:
  title: "Métodos Numéricos con Python"
  author: "Marcos Prunello"
  date: today
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_ecuaciones.qmd
    - 03_sistemas_lineales.qmd
    - 04_sistemasnolineales.qmd
    - 05_autovalores.qmd
    - 06_aprox_polin_parte1.qmd
    - 06_aprox_polin_parte2.qmd
  search: true
  repo-url: https://github.com/mpru/metodos_numericos/
  repo-actions: [edit, issue, source]
  downloads: [pdf]
  sharing: [twitter, facebook]

# language:
#   label:
#     fig: "Figura "
#     tab: "Tabla "
#   ui:
#     chapter_name: ""

# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex

editor: source

execute:
  freeze: auto
  
comments:
  hypothesis: true

