<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.467">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Métodos Numéricos con Python - 1&nbsp; Aproximación polinomial - Parte 1: interpolación</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06_aprox_polin_parte1.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Aproximación polinomial - Parte 1: interpolación</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Métodos Numéricos con Python</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/mpru/metodos_numericos/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Métodos-Numéricos-con-Python.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_aprox_polin_parte1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Aproximación polinomial - Parte 1: interpolación</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1.1</span> Introducción</a></li>
  <li><a href="#polinomios-de-interpolación-de-lagrange" id="toc-polinomios-de-interpolación-de-lagrange" class="nav-link" data-scroll-target="#polinomios-de-interpolación-de-lagrange"><span class="header-section-number">1.2</span> Polinomios de interpolación de Lagrange</a>
  <ul class="collapse">
  <li><a href="#fórmula" id="toc-fórmula" class="nav-link" data-scroll-target="#fórmula"><span class="header-section-number">1.2.1</span> Fórmula</a></li>
  <li><a href="#ejemplo" id="toc-ejemplo" class="nav-link" data-scroll-target="#ejemplo"><span class="header-section-number">1.2.2</span> Ejemplo</a></li>
  <li><a href="#error-de-aproximación" id="toc-error-de-aproximación" class="nav-link" data-scroll-target="#error-de-aproximación"><span class="header-section-number">1.2.3</span> Error de aproximación</a></li>
  <li><a href="#ventajas-y-desventajas" id="toc-ventajas-y-desventajas" class="nav-link" data-scroll-target="#ventajas-y-desventajas"><span class="header-section-number">1.2.4</span> Ventajas y desventajas</a></li>
  </ul></li>
  <li><a href="#polinomios-de-interpolación-de-newton" id="toc-polinomios-de-interpolación-de-newton" class="nav-link" data-scroll-target="#polinomios-de-interpolación-de-newton"><span class="header-section-number">1.3</span> Polinomios de interpolación de Newton</a>
  <ul class="collapse">
  <li><a href="#diferencias-divididas" id="toc-diferencias-divididas" class="nav-link" data-scroll-target="#diferencias-divididas"><span class="header-section-number">1.3.1</span> Diferencias divididas</a></li>
  <li><a href="#fórmula-general-de-newton-para-la-interpolación-con-diferencias-divididas" id="toc-fórmula-general-de-newton-para-la-interpolación-con-diferencias-divididas" class="nav-link" data-scroll-target="#fórmula-general-de-newton-para-la-interpolación-con-diferencias-divididas"><span class="header-section-number">1.3.2</span> Fórmula general de Newton para la interpolación con diferencias divididas</a></li>
  <li><a href="#diferencias-ordinarias" id="toc-diferencias-ordinarias" class="nav-link" data-scroll-target="#diferencias-ordinarias"><span class="header-section-number">1.3.3</span> Diferencias ordinarias</a></li>
  <li><a href="#fórmula-de-interpolación-de-newton-con-diferencias-hacia-adelante" id="toc-fórmula-de-interpolación-de-newton-con-diferencias-hacia-adelante" class="nav-link" data-scroll-target="#fórmula-de-interpolación-de-newton-con-diferencias-hacia-adelante"><span class="header-section-number">1.3.4</span> Fórmula de interpolación de Newton con diferencias hacia adelante</a></li>
  <li><a href="#otras-fórmulas-de-interpolación-de-newton" id="toc-otras-fórmulas-de-interpolación-de-newton" class="nav-link" data-scroll-target="#otras-fórmulas-de-interpolación-de-newton"><span class="header-section-number">1.3.5</span> Otras fórmulas de interpolación de Newton</a></li>
  </ul></li>
  <li><a href="#observaciones-finales" id="toc-observaciones-finales" class="nav-link" data-scroll-target="#observaciones-finales"><span class="header-section-number">1.4</span> Observaciones finales</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/mpru/metodos_numericos/edit/main/06_aprox_polin_parte1.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/mpru/metodos_numericos/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/mpru/metodos_numericos/blob/main/06_aprox_polin_parte1.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Aproximación polinomial - Parte 1: interpolación</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">1.1</span> Introducción</h2>
<ul>
<li><p>Una de las clases más útiles y conocidas de funciones que mapean el conjunto de números reales en sí mismo son los <strong>polinomios algebraicos</strong>:</p>
<p><span class="math display">\[
  P_n(x) = a_{n} x^{n} +a_{n-1} x^{n-1} +...+a_{1} x + a_0
  \]</span></p>
<p>donde <span class="math inline">\(n\)</span> es un entero positivo y <span class="math inline">\(a_0, ..., a_n\)</span> son constantes reales.</p></li>
<li><p>Una razón de su importancia es que se aproximan de manera uniforme a las funciones continuas.</p></li>
<li><p>Es decir, dada una función definida y continua sobre un intervalo cerrado y acotado, existe un polinomio que está tan “cerca” de la función dada como se desee. <strong>Ver teorema 3.1 (Weierstrass) y Figura 3.1 (página 78)</strong>.</p></li>
<li><p>Por esta razón, empleamos polinomios para aproximar el valor de una función <span class="math inline">\(f(x)\)</span> en un intervalo de interés (es decir, para realizar <strong>interpolación</strong>) y también para aproximar derivadas e integrales.</p></li>
<li><p>Englobamos a las técnicas que permiten cumplir con esos objetivos bajo el nombre de <strong>métodos de aproximación polinomial</strong>.</p></li>
<li><p><strong>Observación</strong>: los polinomios de Taylor son esenciales en muchos aspectos del análisis numérico porque permiten aproximar el valor de una función alrededor de un punto específico. Sin embargo, la aproximación polinomial no se basa en el uso de polinomios de Taylor. Leer páginas 78 y 79.</p></li>
<li><p>En este apunte vamos a tratar el tema de la interpolación.</p></li>
<li><p>Preparativos para los ejemplos en Python:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Algunas librerías y funciones necesarias</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> unidad6_funciones <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy.polynomial.polynomial <span class="im">as</span> npol</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="polinomios-de-interpolación-de-lagrange" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="polinomios-de-interpolación-de-lagrange"><span class="header-section-number">1.2</span> Polinomios de interpolación de Lagrange</h2>
<section id="fórmula" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="fórmula"><span class="header-section-number">1.2.1</span> Fórmula</h3>
<ul>
<li>Vamos a considerar el problema en el que contamos con los valores que toma una función de interés <span class="math inline">\(f\)</span> en los <span class="math inline">\(n+1\)</span> puntos <span class="math inline">\(x_0, x_1, ..., x_n\)</span> (es decir, conocemos <span class="math inline">\(f(x_0), ..., f(x_n)\)</span>) y queremos aproximar el valor de <span class="math inline">\(f(x)\)</span> para otros valores <span class="math inline">\(x\)</span>.</li>
</ul>
<div class="alert alert-success">
<p><strong>Definición</strong>: la <strong>interpolación</strong> es el uso de polinomios que coinciden con una función <span class="math inline">\(f\)</span> en puntos determinados dentro de un intervalo para aproximar el valor de <span class="math inline">\(f\)</span> en otros puntos dentro del mismo intervalo.</p>
</div>
<ul>
<li>A los valores <span class="math inline">\(x_i\)</span> para los cuales tenemos <span class="math inline">\(f(x_i)\)</span> les decimos <strong>nodos</strong> y a estos pares de valores los presentamos en una tabla como la siguiente:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="Plots/U6/dif0.png" class="img-fluid" style="width:20.0%"></p>
</div>
</div>
<!-- tabla en md 
|$i$|$x_i$|$f(x_i)$|
|:-:|:-:|:-:|
|$0$|$x_0$|$f(x_0)$|
|$1$|$x_1$|$f(x_1)$|
|$\vdots$|$\vdots$|$\vdots$|
|$n$|$x_n$|$f(x_n)$|
-->
<ul>
<li><p>Por ejemplo:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">i</th>
<th style="text-align: center;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(f(x_i)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">0.5403</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1.0000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">-0.4162</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">-0.8011</td>
</tr>
</tbody>
</table></li>
<li><p>Pensemos en que estamos estudiando una función <span class="math inline">\(f\)</span> para la cual conocemos los valores <span class="math inline">\(f(x_0)\)</span> y <span class="math inline">\(f(x_1)\)</span> y necesitamos aproximar cuánto vale <span class="math inline">\(f(x)\)</span> para algún <span class="math inline">\(x\)</span> entre <span class="math inline">\(x_0\)</span> y <span class="math inline">\(x_1\)</span>.</p></li>
<li><p>¿Qué se nos ocurre hacer?</p></li>
<li><p>Podemos trazar una recta que una los puntos <span class="math inline">\((x_0, f(x_0))\)</span> y <span class="math inline">\((x_1, f(x_1))\)</span> y utilizar como aproximación el valor de esta recta para el <span class="math inline">\(x\)</span> de interés.</p></li>
<li><p>Eso equivale a utilizar un polinomio de grado 1 (una recta) para hacer la interpolación.</p></li>
<li><p>De nuestros conocimientos de geometría sabemos que la ecuación de la recta que pasa por dos puntos <span class="math inline">\((x_0, f(x_0))\)</span> y <span class="math inline">\((x_1, f(x_1))\)</span> es:</p>
<p><span class="math display">\[
  P_1(x) = f(x_0) + \frac{f(x_1) - f(x_0)}{x_1 - x_0} (x - x_0)
  \]</span></p></li>
<li><p>Esto se puede reescribir como:</p>
<p><span class="math display">\[
  P_1(x) = \underbrace{\frac{x - x_1}{x_0 - x_1}}_{L_0(x)} f(x_0) + \underbrace{\frac{x - x_0}{x_1 - x_0}}_{L_1(x)} f(x_1) = L_0(x) f(x_0) + L_1(x) f(x_1)
  \]</span></p></li>
<li><p>Podemos comprobar que dicha recta para por <span class="math inline">\((x_0, f(x_0))\)</span> y <span class="math inline">\((x_1, f(x_1))\)</span> (sustituir <span class="math inline">\(x\)</span> y verificar).</p></li>
<li><p><strong>Importante</strong>: <span class="math inline">\(P(x)\)</span> es el único polinomio de grado 1 que pasa por dichos puntos. Podríamos reescribirlo de muchas formas, pero es un polinomio único (en este caso, es la única recta).</p></li>
<li><p>Esta expresión se puede extender para obtener polinomios de grados superiores que pasen por más puntos.</p></li>
<li><p>Por ejemplo, el polinomio que pasa por los puntos <span class="math inline">\((x_0, f(x_0))\)</span>, <span class="math inline">\((x_1, f(x_1))\)</span> y <span class="math inline">\((x_2, f(x_2))\)</span> es:</p></li>
</ul>
<p><span class="math display">\[
P_2(x) =
\underbrace{\frac{(x - x_1)(x - x_2)}{(x_0 - x_1)(x_0 - x_2)}}_{L_0(x)} f(x_0) +
\underbrace{\frac{(x - x_0)(x - x_2)}{(x_1 - x_0)(x_1 - x_2)}}_{L_1(x)} f(x_1) +
\underbrace{\frac{(x - x_0)(x - x_1)}{(x_2 - x_0)(x_2 - x_1)}}_{L_2(x)} f(x_2)
\]</span></p>
<ul>
<li><p>Se puede ver fácilmente que este polinomio pasa exactamente por los tres puntos dados.</p></li>
<li><p>De la misma forma, el polinomio de grado 3 que pasa por cuatro puntos <span class="math inline">\((x_0, f(x_0))\)</span>, <span class="math inline">\((x_1, f(x_1))\)</span>, <span class="math inline">\((x_2, f(x_2))\)</span> y <span class="math inline">\((x_3, f(x_3))\)</span> es:</p></li>
</ul>
<p><span class="math display">\[
\begin{split}
P_3(x) = &amp;~ \frac{(x - x_1)(x - x_2)(x - x_3)}{(x_0 - x_1)(x_0 - x_2)(x_0 - x_3)} f(x_0) + \frac{(x - x_0)(x - x_2)(x - x_3)}{(x_1 - x_0)(x_1 - x_2)(x_1 - x_3)} f(x_1) \\
&amp; + \frac{(x - x_0)(x - x_1)(x - x_3)}{(x_2 - x_0)(x_2 - x_1)(x_2 - x_3)} f(x_2) + \frac{(x - x_0)(x - x_1)(x - x_2)}{(x_3 - x_0)(x_3 - x_1)(x_3 - x_2)} f(x_3)
\end{split}
\]</span></p>
<ul>
<li><p>Se puede ver fácilmente que este polinomio pasa exactamente por los cuatro puntos dados.</p></li>
<li><p>Generalizando la idea anterior se obtiene la fórmula de interpolación de Lagrange.</p></li>
</ul>
<div class="alert alert-success">
<p><strong>Teorema</strong>: Si <span class="math inline">\(x_0, x_1, ..., x_n\)</span> son <span class="math inline">\(n+1\)</span> números distintos y <span class="math inline">\(f\)</span> es una función cuyos valores están determinados en estos números, entonces existe un único polinomio <span class="math inline">\(P(x)\)</span> de grado a lo sumo <span class="math inline">\(n\)</span> con</p>
<p><span class="math display">\[
f(x_k) = P(x_k) \qquad \forall \, k = 0, 1, ..., n
\]</span></p>
<p>Este polinomio recibe el nombre de <strong>enésimo polinomio de interpolación de Lagrange</strong> y está determinado por:</p>
<p><span class="math display">\[
P_n(x) =  L_{n,0}(x) f(x_0) + ... + L_{n,n}(x) f(x_n) = \sum_{k=0}^{n} f(x_k) L_{n,k}(x),
\]</span></p>
<p>donde para cada <span class="math inline">\(k=0,1, ..., n\)</span>:</p>
<p><span class="math display">\[
L_{n,k}(x) =
\frac{(x-x_0)(x-x_1)...(x-x_{k-1})(x-x_{k+1})...(x-x_{n})}
{(x_k-x_0)(x_k-x_1)...(x_k-x_{k-1})(x_k-x_{k+1})...(x_k-x_{n})}
= \prod^{n}_{\substack{i=0 \\ i \neq k}} \frac{x-x_i}{x_k-x_i}
\]</span></p>
</div>
<ul>
<li><p>Cuando no hay confusión acerca del valor de <span class="math inline">\(n\)</span> escribimos directamente <span class="math inline">\(L_k(x)\)</span> en lugar de <span class="math inline">\(L_{n,k}(x)\)</span>.</p></li>
<li><p>La función <span class="math inline">\(L_{n,k}(x)\)</span> hace que el polinomio pase por los puntos dados debido a que <span class="math inline">\(L_{n,k}(x_i) = 0\)</span> cuando <span class="math inline">\(i\neq k\)</span> y <span class="math inline">\(L_{n,k}(x_k) = 1\)</span> cuando <span class="math inline">\(i = k\)</span>.</p></li>
</ul>
</section>
<section id="ejemplo" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="ejemplo"><span class="header-section-number">1.2.2</span> Ejemplo</h3>
<ul>
<li><p>Emplear el método de Lagrange para interpolar el valor de la función <span class="math inline">\(f\)</span> en <span class="math inline">\(x=2.25\)</span>, con el polinomio interpolante de grado 3 que pasa por los cuatro puntos tabulados:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">i</th>
<th style="text-align: center;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(f(x_i)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">0.5403</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1.0000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">-0.4162</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">-0.8011</td>
</tr>
</tbody>
</table></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un DataFrame con los datos</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>datos <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>: [<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="fl">2.5</span>], <span class="st">'y'</span>: [<span class="fl">0.5403</span>, <span class="dv">1</span>, <span class="op">-</span><span class="fl">0.4162</span>, <span class="op">-</span><span class="fl">0.8011</span>]})</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p><span class="math display">\[
\begin{split}
P_3(x) &amp;=  \sum_{k=0}^{3} f(x_k) \Big(  \prod^{3}_{\substack{i=0 \\ i \neq k}} \frac{x-x_i}{x_k-x_i} \Big) \\
&amp;= f(x_0) \frac{(x - x_1)(x - x_2)(x - x_3)}{(x_0 - x_1)(x_0 - x_2)(x_0 - x_3)}  \\ \\
&amp;+f(x_1) \frac{(x - x_0)(x - x_2)(x - x_3)}{(x_1 - x_0)(x_1 - x_2)(x_1 - x_3)}  \\ \\
&amp;+f(x_2)\frac{(x - x_0)(x - x_1)(x - x_3)}{(x_2 - x_0)(x_2 - x_1)(x_2 - x_3)}   \\ \\
&amp;+f(x_3)\frac{(x - x_0)(x - x_1)(x - x_2)}{(x_3 - x_0)(x_3 - x_1)(x_3 - x_2)} \\ \\
\implies P_3(2.25) =&amp;
0.5403 \times\frac{(2.25 - 0)(2.25 - 2)(2.25 - 2.5)}{(-1-0)(-1-2)(-1-2.5)}  \\ \\
&amp;+ 1\times\frac{(2.25 +1)(2.25 - 2)(2.25 - 2.5)}{(0+1)(0-2)(0-2.5)}  \\ \\
&amp;-0.4162\times\frac{(2.25 +1)(2.25 - 0)(2.25 - 2.5)}{(2+1)(2-0)(2-2.5)}  \\ \\
&amp;-0.8011 \times\frac{(2.25 +1)(2.25 - 0)(2.25 - 2)}{(2.5+1)(2.5-0)(2.5-2)}  = \\ \\
&amp;= -0.6217561 \\ \\
&amp;\therefore f(2.25) \approx -0.6217561
\end{split}
\]</span></p>
<ul>
<li>La fórmula fue programada en la función provista <code>lagrange()</code>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="fl">2.5</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>fx <span class="op">=</span> np.array([<span class="fl">0.5403</span>, <span class="dv">1</span>, <span class="op">-</span><span class="fl">0.4162</span>, <span class="op">-</span><span class="fl">0.8011</span>])</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>lagrange(x, fx, <span class="fl">2.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-0.6217560714285715</code></pre>
</div>
</div>
<ul>
<li><p>Si en la fórmula anterior en lugar de reemplazar <span class="math inline">\(x\)</span> por un valor particular (en este caso, <span class="math inline">\(2.25\)</span>) operamos y re acomodamos los términos, podemos hallar la expresión del polinomio interpolante:</p>
<p><span class="math display">\[
  P_3(x) = 0.1042 x^3 -0.4934 x^2 -0.1379 x+1
  \]</span></p></li>
<li><p>Podemos graficar este polinomio para ver lo que ha logrado este método:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir la función p3 como una función lambda</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>p3 <span class="op">=</span> <span class="kw">lambda</span> x: <span class="fl">0.1042</span> <span class="op">*</span> x<span class="op">**</span><span class="dv">3</span> <span class="op">-</span> <span class="fl">0.4934</span> <span class="op">*</span> x<span class="op">**</span><span class="dv">2</span> <span class="op">-</span> <span class="fl">0.1379</span> <span class="op">*</span> x <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un rango de valores para x</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>rango_x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">1.2</span>, <span class="fl">2.7</span>, <span class="dv">100</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular los valores correspondientes de p3</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> p3(rango_x)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y, label<span class="op">=</span><span class="st">"Polinomio interpolante"</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid" width="768"></p>
</div>
</div>
<ul>
<li>En Python podemos usar la función <code>polyfit()</code> de la librería <code>numpy.polynomial.polynomial</code> para obtener la expresión del polinomio interpolante de Lagrange y realizar interpolaciones, pero como siempre escribimmos nuestras propias funciones para entender lo que hacen los métodos y repasar programación:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar un polinomio a los datos</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="fl">2.5</span>])</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>fx <span class="op">=</span> np.array([<span class="fl">0.5403</span>, <span class="dv">1</span>, <span class="op">-</span><span class="fl">0.4162</span>, <span class="op">-</span><span class="fl">0.8011</span>])</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes del polinomio (menor a mayor grado)</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>coefs <span class="op">=</span> npol.polyfit(x, fx, deg <span class="op">=</span> <span class="bu">len</span>(x) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(coefs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[ 1.         -0.1379019  -0.49343429  0.10416762]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir esos coeficientes en una función polinómica</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>poli <span class="op">=</span> npol.Polynomial(coefs)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la expresion del polinomio</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poli)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.0 - 0.1379019·x - 0.49343429·x² + 0.10416762·x³</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluar el polinomio interpolante en el punto 2.25</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>poli(<span class="fl">2.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-0.6217560714285701</code></pre>
</div>
</div>
<ul>
<li>La verdadera función que generó los valores tabulados es <span class="math inline">\(cos(x)\)</span>. Podemos compararla con el polinomio interpolante:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>y_cos <span class="op">=</span> np.cos(rango_x)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y, label<span class="op">=</span><span class="st">"Polinomio interpolante"</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y_cos, label<span class="op">=</span><span class="st">"Coseno"</span>, color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-8-5.png" class="img-fluid" width="768"></p>
</div>
</div>
<ul>
<li>Ojo, si nos alejamos del rango estudiado, el polinomio no tiene por qué aproximar bien (cuidado con la extrapolación)…</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Función verdadera (coseno) y polinimo interpolante fuera del rango de puntos</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># disponibles</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>rango_x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">100</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>y_cos <span class="op">=</span> np.cos(rango_x)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> p3(rango_x)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y, label<span class="op">=</span><span class="st">"Polinomio interpolante"</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y_cos, label<span class="op">=</span><span class="st">"Coseno"</span>, color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="op">-</span><span class="dv">6</span>, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(-6.0, 6.0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-9-7.png" class="img-fluid" width="768"></p>
</div>
</div>
</section>
<section id="error-de-aproximación" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="error-de-aproximación"><span class="header-section-number">1.2.3</span> Error de aproximación</h3>
<ul>
<li><p>En el ejemplo, sabiendo el verdadero valor <span class="math inline">\(cos(2.25) = -0.6281736\)</span>, podemos calcular el error absoluto:</p>
<p><span class="math display">\[|-0.6281736+0.6217561| = 0.0064175\]</span></p>
<p>y el error relativo:</p>
<p><span class="math display">\[\frac{|-0.6281736+0.6217561|}{|-0.6281736|} = 1.021612\%\]</span></p></li>
<li><p>En una situación práctica donde no tenemos el verdadero <span class="math inline">\(f(x)\)</span>, vale el siguiente resultado.</p></li>
<li><p>Se puede demostrar (ver opcionalemente Teorema 3.3) que el error en la aproximación con el polinomio de Lagrange está dado por:</p>
<p><span class="math display">\[
f(x) - P_n(x) = \frac{f^{(n+1)}(\xi)}{(n+1)!}(x-x_0)(x-x_1)...(x-x_n)
\]</span></p>
<p>donde <span class="math inline">\(\xi\)</span> es algún número dentro del intervalo en el que se encuentran los nodos <span class="math inline">\(x_i\)</span>.</p></li>
</ul>
<ul>
<li><p>Para saber cuál es la cota superior del error se busca acotar la expresión anterior para cualquier <span class="math inline">\(\xi\)</span> dentro del rango estudiado (ver opcionalmente ejemplos 3 y 4).</p></li>
<li><p>En el ejemplo nuestro, siendo <span class="math inline">\(f(x) = cos(x)\)</span>, <span class="math inline">\(n=3\)</span> y <span class="math inline">\(f^{(4)}(x) = cos(x)\)</span>:</p>
<p><span class="math display">\[
f(x) - P_n(x) = \frac{cos(\xi)}{4!}(x+1)x(x-2)(x-2.5) \qquad -1 \leq \xi \leq 2.5
\]</span></p></li>
<li><p>Sabiendo que <span class="math inline">\(|cos(\xi)| \leq 1\)</span>, encontramos una cota superior para el error de aproximación:</p>
<p><span class="math display">\[
|f(x) - P_n(x)| \leq \Big|\frac{1}{4!}(x+1)x(x-2)(x-2.5)\Big|
\]</span></p></li>
<li><p>Para el punto analizado <span class="math inline">\(x=2.25\)</span> esa cota superior nos da <span class="math inline">\(0.01904297\)</span> (y efectivamente el error absoluto, que lo pudimos calcular, era menor que esto).</p></li>
<li><p>Este resultado es muy importante porque permite evaluar el desempeño de la aproximación pero muchas veces es impracticable porque no se conoce cuál es la derivada <span class="math inline">\(f^{(n+1)}\)</span>, por lo tanto tiene utilidad teórica pero no práctica.</p></li>
<li><p>En esos casos, sólo es posible evaluar la precisión al comparar las aproximaciones obtenidas con polinomios de distinto grado (ver ejemplo en la sección “Ilustración” en páginas 86 y 87).</p></li>
</ul>
<!-- -   Si teniendo $n+1$ puntos ajustamos un polinomio de grado menor a $n$, podemos tomar como aproximación del error al valor del término siguiente en la fórmula. -->
<!-- -   Esto se conoce como **regla del término siguiente** y su justificación radica en el hecho de que hay una relación entre la derivada de $f$ (de la cual depende el error) y las diferencias divididas. -->
<!-- -   Por eso, comparar sucesivas aproximaciones da una idea de la magnitud del error cometido. -->
</section>
<section id="ventajas-y-desventajas" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="ventajas-y-desventajas"><span class="header-section-number">1.2.4</span> Ventajas y desventajas</h3>
<ul>
<li><p><strong>Ventajas</strong>:</p>
<ul>
<li>Una ventaja de este método de Lagrange es que provee de una forma sencilla una expresión explícita para el polinomio de interpolación.</li>
<li>Además, no requiere que los puntos <span class="math inline">\(x_i\)</span> estén ordenados ni sean equiespaciados.</li>
</ul></li>
<li><p><strong>Desventaja</strong>:</p>
<ul>
<li>Dado que el término de error difícilmente puede ser construído, generalmente se necesitan considerar varios polinomios de interpolación de distinto grado para comparar las aproximaciones logradas.</li>
<li>Sin embargo, con el método de Lagrange no hay relación entre la construcción de un polinomio de un grado <span class="math inline">\(n\)</span> y otro de grado <span class="math inline">\(n+1\)</span>; cada polinomio debe construirse individualmente realizando todos los cálculos otra vez, lo cual resulta laborioso y poco eficiente.</li>
</ul></li>
<li><p>El <strong>Método de Neville</strong> (no lo estudiaremos) soluciona este inconveniente, reformulando los cálculos para poder obtener aproximaciones usando cálculos previos. Una aproximación de grado <span class="math inline">\(n+1\)</span> se logra tomando la de grado <span class="math inline">\(n\)</span> y sumándole otro término.</p></li>
<li><p>Sin embargo, este método no permite obtener una expresión explícita del polinomio.</p></li>
<li><p>Para poder generar sucesivamente los polinomios interpolantes se puede recurrir a los métodos de <strong>diferencias de Newton</strong> que se presentan en la siguiente sección.</p></li>
</ul>
</section>
</section>
<section id="polinomios-de-interpolación-de-newton" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="polinomios-de-interpolación-de-newton"><span class="header-section-number">1.3</span> Polinomios de interpolación de Newton</h2>
<ul>
<li>A pesar de que el polinomio que <span class="math inline">\(P_n(x)\)</span> que concuerda con la función <span class="math inline">\(f\)</span> en <span class="math inline">\(x_0, ..., x_n\)</span> es único, existen diferentes representaciones algebraicas que son útiles en distintas situaciones y la fórmula de Lagrange es sólo una de ellas.</li>
<li>Para poder generer polinomios interpolantes con otra expresión que admita cálculos recursivos (es decir, aprovechando los cálculos hechos para polinomios de menor grado), vamos a necesitar obtener una <strong>tabla de diferencias divididas</strong> y una <strong>tabla de diferencias ordinarias</strong>.</li>
</ul>
<section id="diferencias-divididas" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="diferencias-divididas"><span class="header-section-number">1.3.1</span> Diferencias divididas</h3>
<ul>
<li>Presentar formalmente a las <strong>diferencias divididas</strong> es más difícil que calcularlas.</li>
</ul>
<div class="alert alert-success">
<p><strong>Definición</strong>:</p>
<ul>
<li><p>La <em>cero-ésima diferencia dividida</em> de la función <span class="math inline">\(f\)</span> respecto a <span class="math inline">\(x_i\)</span> es: <span class="math inline">\(f[x_i] = f(x_i)\)</span>.</p></li>
<li><p>La <em>primera diferencia dividida</em> de <span class="math inline">\(f\)</span> respecto a <span class="math inline">\(x_i\)</span> y <span class="math inline">\(x_{i+1}\)</span> es:</p>
<p><span class="math display">\[
  f[x_i, x_{i+1}] = \frac{f[x_{i+1}] - f[x_i]}{x_{i+1} - x_i}
  \]</span></p></li>
<li><p>La <em>segunda diferencia dividida</em> de <span class="math inline">\(f\)</span> respecto a <span class="math inline">\(x_i\)</span>, <span class="math inline">\(x_{i+1}\)</span> y <span class="math inline">\(x_{i+2}\)</span> es:</p>
<p><span class="math display">\[
  f[x_i, x_{i+1}, x_{i+2}] = \frac{f[x_{i+1},x_{i+2}] - f[x_{i},x_{i+1}]}{x_{i+2} - x_i}
  \]</span></p></li>
<li><p>De manera general, después de haber calculado las <span class="math inline">\(k-1\)</span> diferencias divididas:</p>
<p><span class="math display">\[
  f[x_i, ..., x_{i+k-1}] \quad \text{ y } \quad f[x_{i+1}, ..., x_{i+k}],
  \]</span></p>
<p>la <span class="math inline">\(k\)</span>-ésima diferencia dividida relativa a <span class="math inline">\(x_i, ..., x_{i+k}\)</span> es:</p>
<p><span class="math display">\[
  f[x_i, ..., x_{i+k}] = \frac{f[x_{i+1}, ..., x_{i+k}] - f[x_i, ..., x_{i+k-1}]}{x_{i+k} - x_i}
  \]</span></p></li>
</ul>
<!-- - Finalmente, la $n$-ésima diferencia dividida relativa a $x_i, ..., x_{i+k}$ es: -->
</div>
<ul>
<li>Lo anterior es más claro si lo presentamos en una <strong>tabla de diferencias divididas</strong>.</li>
<li>Por ejemplo, con 6 puntos:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="Plots/U6/dif1.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<ul>
<li><p>La tabla anterior podría llegar hasta las quintas diferencias divididas.</p></li>
<li><p><strong>En general, si contamos con <span class="math inline">\(n+1\)</span> puntos, podemos calcular hasta las diferencias divididas de orden <span class="math inline">\(n\)</span></strong>.</p></li>
</ul>
</section>
<section id="fórmula-general-de-newton-para-la-interpolación-con-diferencias-divididas" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="fórmula-general-de-newton-para-la-interpolación-con-diferencias-divididas"><span class="header-section-number">1.3.2</span> Fórmula general de Newton para la interpolación con diferencias divididas</h3>
<ul>
<li>Para poder generar polinomios interpolantes de distinto orden recursivamente Newton propone emplear la siguiente representación para <span class="math inline">\(P_n(x)\)</span>:</li>
</ul>
<span class="math display">\[\begin{equation}
\label{eq:eq1}
P_n(x) = a_0 + a_1 (x - x_0) + a_2 (x-x_0)(x-x_1)+...+a_n(x-x_0)...(x-x_{n-1})
\end{equation}\]</span>
<ul>
<li><p>De hecho, antes repasamos la fórmula de la recta (polinomio interpolante de grado 1) que pasa por dos puntos y estaba escrita de esa forma:</p>
<p><span class="math display">\[
  P_1(x) = \underbrace{f(x_0)}_{a_0} + \underbrace{\frac{f(x_1) - f(x_0)}{x_1 - x_0}}_{a_1} (x - x_0)
  \]</span></p></li>
<li><p>Si miramos bien, tenemos que notar que <span class="math inline">\(a_0\)</span> y <span class="math inline">\(a_1\)</span> coinciden con la definición de <strong>diferencias divididas</strong> para <span class="math inline">\(x_0\)</span> de orden 0 y 1, respectivamente.</p></li>
<li><p>De manera general, se puede probar que las constantes <span class="math inline">\(a_k\)</span> necesarias para expresar <span class="math inline">\(P_n(x)\)</span> de la forma deseada <span class="math inline">\(\eqref{eq:eq1}\)</span> son las diferencias divididas <span class="math inline">\(a_k = f[x_0, ...,x_k]\)</span>, haciendo que el polinomio quede así:</p>
<span class="math display">\[\begin{equation}
  \label{eq:eq2}
  P_n(x) = f[x_0] + \sum_{k=1}^{n} f[x_0,..., x_k] (x-x_0)...(x-x_{k-1})
\end{equation}\]</span></li>
<li><p>Es decir, se usan las diferencias divididas que están en la diagonal de la tabla.</p></li>
<li><p><strong>Ejemplo</strong>. Retomamos el ejemplo anterior. A continuación se presentan los puntos tabulados junto con las diferencias divididas. Los valores en negrita son los que se utilizan en la fórmula. Verificar los cálculos a mano.</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 32%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">i</th>
<th style="text-align: center;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(f(x_i)\)</span></th>
<th style="text-align: center;">Primeras diferencias</th>
<th style="text-align: center;">Segundas diferencias</th>
<th style="text-align: center;">Terceras diferencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;"><strong>0.5403</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>0.4597</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1.0000</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>-0.3893</strong></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.7081</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>0.1042</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">-0.4162</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.0247</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.7698</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">-0.8011</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table></li>
<li><p>En Python vamos a usar la función provista <code>diferencias()</code> para obtener este resultado:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>diferencias(fx, x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([[ 0.5403    ,  0.4597    , -0.38926667,  0.10416762],
       [ 1.        , -0.7081    , -0.02468   ,         nan],
       [-0.4162    , -0.7698    ,         nan,         nan],
       [-0.8011    ,         nan,         nan,         nan]])</code></pre>
</div>
</div>
<ul>
<li><p>Vamos emplear el método de las diferencias divididas de Newton para interpolar el valor de la función <span class="math inline">\(f\)</span> en <span class="math inline">\(x=2.25\)</span>, con el polinomio interpolante de grado 3 que pasa por los cuatro puntos tabulados:</p>
<p><span class="math display">\[
  \begin{split}
  P_3(x) &amp;= f[x_0] + \sum_{k=1}^{3} f[x_0,..., x_k] (x-x_0)...(x-x_{k-1}) \\\\
  &amp;= 0.5403 \\\\
  &amp;+ 0.4597 (x+1) \\\\
  &amp;- 0.3893 (x+1)x \\\\
  &amp;+ 0.1042 (x+1)x(x-2) \\\\
  \implies P_3(2.25) &amp;= -0.6217561
  \end{split}
  \]</span></p></li>
<li><p>En Python lo vamos a aplicar en la función <code>newton_general()</code> (provista en el archivo de funciones):</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>newton_general(x, fx, valor <span class="op">=</span> <span class="fl">2.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-0.6217560714285713</code></pre>
</div>
</div>
<ul>
<li>Como el polinomio de grado 3 que pasa por 4 puntos es único, este resultado coincide con el del método de Lagrange.</li>
<li>Sin embargo, tiene una ventaja importante. No siempre es necesario ni conveniente ajustar el polinomio de mayor orden posible, pero probar con distintos grados es muy laborioso en el método de Lagrange.</li>
<li>En cambio este método lo vuelve más sencillo, porque pasamos de una aproximación de un grado menor a otra de un grado superior solamente sumando un término más en la cuenta. Se aprovechan los cálculos anteriores. Entonces:</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Grado</th>
<th style="text-align: center;"><span class="math inline">\(P_n(2.25) =\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(f[x_0] + f[x_0, x_1] (x-x_0) = 2.0343\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(2.0343 + f[x_0, x_1, x_2] (x-x_0)(x-x_1) = -0.8124\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(-0.8124 + f[x_0, x_1, x_2, x_3] (x-x_0)(x-x_1)(x-x_3) = -0.6218\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li>En Python:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> grado <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">4</span>):</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(newton_general(x, fx, valor <span class="op">=</span> <span class="fl">2.25</span>, g <span class="op">=</span> grado))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.034325
-0.8121874999999998
-0.6217560714285713</code></pre>
</div>
</div>
<ul>
<li>La primera aproximación es una interpolación lineal y pasa por los primeros dos puntos; la segunda es cuadrática y pasa por los primeros tres puntos y la última es cúbica y pasa por todos los puntos:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<ul>
<li>Es claro que la aproximación lineal anterior no es buena para <span class="math inline">\(x=2.25\)</span>.</li>
<li>Sin embargo, una recta que pase por los últimos dos puntos podría tener un desempeño similar al del polinomio de grado 3:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>newton_general(x[<span class="dv">2</span>:], fx[<span class="dv">2</span>:], <span class="fl">2.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-0.60865</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># preparar curvas para graficar</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>p1b <span class="op">=</span> npol.Polynomial(npol.polyfit(x[<span class="dv">2</span>:], fx[<span class="dv">2</span>:], deg <span class="op">=</span> <span class="dv">1</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>y_p1b <span class="op">=</span> p1b(rango_x)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y_p1, label<span class="op">=</span><span class="st">"Con x0 = -1"</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y_p1b, label<span class="op">=</span><span class="st">"Con x0 = 2"</span>, color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Polinomios interpolantes de grado 1"</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>plt.axvline(x<span class="op">=</span><span class="fl">2.25</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>plt.scatter([<span class="fl">2.25</span>, <span class="fl">2.25</span>], [p1(<span class="fl">2.25</span>), p1b(<span class="fl">2.25</span>)], color <span class="op">=</span> <span class="st">"orange"</span>, s <span class="op">=</span> <span class="dv">100</span>)</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-17-3.png" class="img-fluid" width="768"></p>
</div>
</div>
<ul>
<li>La expresión anterior facilita la obtención de polinomios interpolantes de diferentes grados, puesto que los mismos sólo se diferencian en términos que se van agregando en la parte de la sumatoria.</li>
<li>Sin embargo, la expresión de la fórmula no deja de ser algo compleja e involucra muchos cálculos.</li>
<li>En el caso de que los nodos <span class="math inline">\(x_i\)</span> están ordenados de menor a mayor y tengan igual espaciado entre ellos, la fórmula se simplifica muchísimo y recibe el nombre de</li>
<li>Pero para conocer esta fórmula necesitamos definir las <strong>diferencias ordinarias</strong>.</li>
</ul>
</section>
<section id="diferencias-ordinarias" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="diferencias-ordinarias"><span class="header-section-number">1.3.3</span> Diferencias ordinarias</h3>
<ul>
<li>Las <strong>diferencias ordinarias</strong> se asemejan a las divididas, pero no hacen la división por las restas entre valores de <span class="math inline">\(x\)</span>.</li>
</ul>
<div class="alert alert-success">
<p><strong>Definición</strong>: las <strong>diferencias ordinarias</strong> se expresan como:</p>
<p><span class="math display">\[
\Delta^{j} f(x_k) = \Delta^{j-1} f(x_{k+1}) - \Delta^{j-1} f(x_k)
\qquad
j = 1, ..., n \qquad k = 0, ..., j-1 \qquad \Delta^{0} f(x_k) = f(x_k)
\]</span></p>
</div>
<ul>
<li>Es decir que las diferencias de orden 0 son los mismos valores <span class="math inline">\(f(x_i)\)</span>, las diferencias de orden 1 son <span class="math inline">\(f(x_{k+1}) - f(x_k)\)</span>, las diferencias de orden 2 son restas con las de orden 1, y así sucesivamente.</li>
<li>Para simplificar la notación, cuando no haya ambigüedad vamos a escribir: <span class="math inline">\(\Delta^{j} f(x_k) = \Delta^j_k\)</span>.</li>
<li>La <strong>tabla de diferencias ordinarias</strong> es:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="Plots/U6/dif2.png" class="img-fluid" style="width:80.0%"></p>
</div>
</div>
<!-- Tabla que puse como imagen

|  $x$  |  $f(x)$  |     Primeras diferencias    |         Segundas diferencias         |         Terceras diferencias         |          Cuartas diferencias         |          Quintas diferencias         |
|:-----:|:--------:|:---------------------------:|:------------------------------------:|:------------------------------------:|:------------------------------------:|:------------------------------------:|
| $x_0$ | $f(x_0)$ |                             |                                      |                                      |                                      |                                      |
|       |          | $\Delta_0^1 =f(x_1)-f(x_0)$ |                                      |                                      |                                      |                                      |
| $x_1$ | $f(x_1)$ |                             | $\Delta^2_0 = \Delta_1^1-\Delta^1_0$ |                                      |                                      |                                      |
|       |          | $\Delta_1^1 =f(x_2)-f(x_1)$ |                                      | $\Delta^3_0 = \Delta^2_1-\Delta^2_0$ |                                      |                                      |
| $x_2$ | $f(x_2)$ |                             | $\Delta^2_1 = \Delta_2^1-\Delta^1_1$ |                                      | $\Delta^4_0 = \Delta^3_1-\Delta^3_0$ |                                      |
|       |          | $\Delta_2^1 =f(x_3)-f(x_2)$ |                                      | $\Delta^3_1 = \Delta^2_2-\Delta^2_1$ |                                      | $\Delta^5_0 = \Delta^4_1-\Delta^4_0$ |
| $x_3$ | $f(x_3)$ |                             | $\Delta^2_2 = \Delta_3^1-\Delta^1_2$ |                                      | $\Delta^4_1 = \Delta^3_2-\Delta^3_1$ |                                      |
|       |          | $\Delta_3^1 =f(x_4)-f(x_3)$ |                                      | $\Delta^3_2 = \Delta^2_3-\Delta^2_2$ |                                      |                                      |
| $x_4$ | $f(x_4)$ |                             | $\Delta^2_3 = \Delta_4^1-\Delta^1_3$ |                                      |                                      |                                      |
|       |          | $\Delta_4^1 =f(x_5)-f(x_4)$ |                                      |                                      |                                      |                                      |
| $x_5$ | $f(x_5)$ |                             |                                      |                                      |                                      |                                      |
-->
<ul>
<li><strong>En general, si contamos con <span class="math inline">\(n+1\)</span> puntos, podemos calcular hasta las diferencias ordinarias de orden <span class="math inline">\(n\)</span></strong>.</li>
</ul>
</section>
<section id="fórmula-de-interpolación-de-newton-con-diferencias-hacia-adelante" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="fórmula-de-interpolación-de-newton-con-diferencias-hacia-adelante"><span class="header-section-number">1.3.4</span> Fórmula de interpolación de Newton con diferencias hacia adelante</h3>
<ul>
<li><p>Veamos cómo la fórmula general de Newton se simplifica para el caso particular en el que los nodos <span class="math inline">\(x_i\)</span> están ordenados de menor a mayor y son equiespaciados.</p></li>
<li><p>Llamamos con <span class="math inline">\(h\)</span> al espaciado uniforme: <span class="math inline">\(h = x_{i+1}-x_i\)</span>, para cada <span class="math inline">\(i=0, 1, ..., n-1\)</span>.</p></li>
<li><p>Cualquier valor <span class="math inline">\(x\)</span> puede ser expresado como <span class="math inline">\(x = x_0 + sh\)</span> y en particular los nodos se pueden escribir como <span class="math inline">\(x_i = x_0 + ih\)</span>.</p></li>
<li><p>Entonces nos queda: <span class="math inline">\(x - x_i = (s-i)h\)</span>.</p></li>
<li><p>Haciendo los reemplazos correspondientes y después de varios pasos algebraicos, <span class="math inline">\(\eqref{eq:eq2}\)</span> nos queda de una forma mucho más compacta:</p>
<p><span class="math display">\[
\begin{aligned}
P_n(x)
&amp;= f(x_0) + s \Delta^1_0 + \frac{s(s-1)}{2!} \Delta^2_0 + \frac{s(s-1)(s-2)}{3!} \Delta^3_0 + ...\\
&amp;= \sum_{k=0}^n {s \choose k} \Delta_0^k
\end{aligned}
\]</span></p>
<p>donde: <span class="math inline">\({s \choose k} = \frac{s(s-1)(s-2)...(s-k+1)}{k!}\)</span>.</p></li>
<li><p>Esta es la <strong>fórmula de interpolación de Newton con diferencias hacia adelante</strong>, porque utiliza la primera diagonal desde arriba a la izquierda hacia abajo a la derecha de la <strong>tabla de diferencias ordinarias</strong>.</p></li>
<li><p>Hay que observar que la fórmula empieza con el valor de <span class="math inline">\(f(x_0)\)</span> y luego continúa empleando las diferencias <span class="math inline">\(\Delta_0^k\)</span>.</p></li>
</ul>
<p><strong>Ejemplo</strong>.</p>
<ul>
<li>Sea <span class="math inline">\(f(x)\)</span> una función desconocida de la cual se tienen los valores tabulados <span class="math inline">\((x_i, f(x_i))\)</span> que se presentan a continuación, junto con una representación gráfica de los mismos:</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(f(x_i)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.3010</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.4771</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.6021</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.6990</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.7781</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0.8451</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un DataFrame con los datos</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>datos <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>: <span class="bu">range</span>(<span class="dv">2</span>, <span class="dv">8</span>), <span class="st">'y'</span>: [<span class="fl">0.3010</span>, <span class="fl">0.4771</span>, <span class="fl">0.6021</span>, <span class="fl">0.6990</span>, <span class="fl">0.7781</span>, <span class="fl">0.8451</span>]})</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>plt.xlim(<span class="op">-</span><span class="fl">0.2</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(-0.2, 8.0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>La correspondiente tabla de diferencias ordinarias es (verificar los cálculos a mano):</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(x_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(f(x_i)\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\Delta^1_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\Delta^2_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\Delta^3_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\Delta^4_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\Delta^5_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><strong>0.3010</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>0.1761</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.4771</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>-0.0511</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.1250</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>0.0230</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.6021</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.0281</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>-0.0127</strong></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.0969</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.0103</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>0.0081</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.6990</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.0178</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.0046</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.0791</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.0057</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.7781</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.0121</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.0670</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0.8451</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<!-- 
| $i$ | $x_i$ |$f(x_i)$| $\Delta^1_i$ | $\Delta^2_i$   | $\Delta^3_i$   | $\Delta^4_i$  | $\Delta^5_i$  | 
|:---:|:-----:|:------:|:------------:|:--------------:|:--------------:|:-------------:|:-------------:|
| 0   | 2     | 0.3010 |              |                |                |               |               |
|     |       |        | 0.1761       |                |                |               |               |
| 1   | 3     | 0.4771 |              | -0.0511        |                |               |               |
|     |       |        | 0.1250       |                | 0.0230         |               |               |
| 2   | 4     | 0.6021 |              | -0.0281        |                | -0.0127       |               |
|     |       |        | 0.0969       |                | 0.0103         |               | 0.0081        |
| 3   | 5     | 0.6990 |              | -0.0178        |                | -0.0046       |               |
|     |       |        | 0.0791       |                | 0.0057         |               |               |
| 4   | 6     | 0.7781 |              | -0.0121        |                |               |               |
|     |       |        | 0.0670       |                |                |               |               |
| 5   | 7     | 0.8451 |              |                |                |               |               |
-->
<ul>
<li>Los valores en negrita son los que utiliza la fórmula.</li>
<li>También usamos la función <code>diferencias()</code> para obtenerla, que devuelve las diferencias ordinarias si no se provee un vector de <span class="math inline">\(x_i\)</span>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>fx <span class="op">=</span> np.array([<span class="fl">.3010</span>, <span class="fl">.4771</span>, <span class="fl">.6021</span>, <span class="fl">.6990</span>, <span class="fl">.7781</span>, <span class="fl">.8451</span>])</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>diferencias(fx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([[ 0.301 ,  0.1761, -0.0511,  0.023 , -0.0127,  0.0081],
       [ 0.4771,  0.125 , -0.0281,  0.0103, -0.0046,     nan],
       [ 0.6021,  0.0969, -0.0178,  0.0057,     nan,     nan],
       [ 0.699 ,  0.0791, -0.0121,     nan,     nan,     nan],
       [ 0.7781,  0.067 ,     nan,     nan,     nan,     nan],
       [ 0.8451,     nan,     nan,     nan,     nan,     nan]])</code></pre>
</div>
</div>
<ul>
<li><p>Vamos a aproximar <span class="math inline">\(f(2.3)\)</span> con un polinomio de grado 5 que pase por todos los puntos provistos:</p>
<ul>
<li><span class="math inline">\(h = 1\)</span> (espaciado)</li>
<li><span class="math inline">\(x=2.3\)</span></li>
<li><span class="math inline">\(x_0 = 2\)</span></li>
<li><span class="math inline">\(s = \frac{x-x_0}{h} = \frac{2.3-2}{1} = 0.3\)</span></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
P_5(x)
&amp;= \sum_{k=0}^5 {s \choose k} \Delta_0^k \\ \\
&amp;= f(x_0) + s \Delta^1_0 + \frac{s(s-1)}{2!} \Delta^2_0 + \frac{s(s-1)(s-2)}{3!} \Delta^3_0 + ...\\ \\
&amp;= 0.3010 \\\\
&amp;+ 0.3 \times 0.1761 \\ \\
&amp;+ \frac{0.3(0.3-1)}{2!} (-0.0511) \\ \\
&amp;+ \frac{0.3(0.3-1)(0.3-2)}{3!} 0.0230 \\ \\
&amp;+ \frac{0.3(0.3-1)(0.3-2)(0.3-3)}{4!} (-0.0127) \\ \\
&amp;+ \frac{0.3(0.3-1)(0.3-2)(0.3-3)(0.3-4)}{5!} 0.0081 \\ \\
\implies P_5(2.3) &amp;= 0.3613
\end{aligned}
\]</span></p></li>
<li><p>En Python vamos a usar la función <code>newton_adelante()</code> (provista):</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>newton_adelante(fx, s <span class="op">=</span> <span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.36131479777500003</code></pre>
</div>
</div>
<ul>
<li>Si en la fórmula anterior reemplazamos <span class="math inline">\(s\)</span> por su defición <span class="math inline">\((x - 2)/1\)</span> y con mucha paciencia operamos en términos de <span class="math inline">\(x\)</span>, podemos encontrar una expresión explícita para el polinomio.</li>
<li>Como vimos antes, en Python lo hacemos con:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="dv">2</span>, <span class="dv">8</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fx <span class="op">=</span> np.array([<span class="fl">.3010</span>, <span class="fl">.4771</span>, <span class="fl">.6021</span>, <span class="fl">.6990</span>, <span class="fl">.7781</span>, <span class="fl">.8451</span>])</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes del polinomio (menor a mayor grado)</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>coefs_g5 <span class="op">=</span> npol.polyfit(x, fx, deg <span class="op">=</span> <span class="bu">len</span>(x) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(coefs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[ 1.         -0.1379019  -0.49343429  0.10416762]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir esos coeficientes en una función polinómica</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>poli_g5 <span class="op">=</span> npol.Polynomial(coefs_g5)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la expresion del polinomio</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poli_g5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-0.4086 + 0.55547833·x - 0.13677083·x² + 0.02170417·x³ - 0.00187917·x⁴ +
(6.75e-05)·x⁵</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluar el polinomio interpolante en el punto 2.3</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>poli_g5(<span class="fl">2.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.3613147977750001</code></pre>
</div>
</div>
<ul>
<li>Luego, lo podemos graficar:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un rango de valores para x</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>rango_x <span class="op">=</span> np.linspace(<span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">100</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular los valores correspondientes</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>y_g5 <span class="op">=</span> poli_g5(rango_x)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>plt.xlim(<span class="op">-</span><span class="fl">0.2</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(-0.2, 8.0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y_g5, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Polinomio interpolante de grado 5"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(<span class="fl">2.3</span>, poli_g5(<span class="fl">2.3</span>), color <span class="op">=</span> <span class="st">"orange"</span>, s <span class="op">=</span> <span class="dv">100</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>plt.axvline(x<span class="op">=</span><span class="fl">2.3</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>Como el polinomio de grado 5 que pasa por 6 puntos es único, la expresión hallada coincide a la que se hubiese obtenido con la fórmula general de Newton o con la de Lagrange.</p></li>
<li><p>¿Es necesario haber empleado un polinomio de grado 5?</p></li>
<li><p>Viendo el gráfico podemos pensar que una función cuadrática puede proveer un buen ajuste.</p></li>
<li><p>Eso tiene la ventaja de ahorrar cálculos y evita acumular errores por redondeo.</p></li>
<li><p>Por eso, podríamos haber propuesto inicialmente un polinomio interpolante de grado 2, que pasa por los primeros 3 puntos, usando hasta la diferencia de segundo orden:</p>
<ul>
<li><span class="math inline">\(h = 1\)</span> (espaciado)</li>
<li><span class="math inline">\(x=2.3\)</span></li>
<li><span class="math inline">\(x_0 = 2\)</span></li>
<li><span class="math inline">\(s = \frac{x-x_0}{h} = \frac{2.3-2}{1} = 0.3\)</span></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
P_2(x)
&amp;= \sum_{k=0}^2 {s \choose k} \Delta_0^k \\ \\
&amp;= f(x_0) + s \Delta^1_0 + \frac{s(s-1)}{2!} \Delta^2_0 \\ \\
&amp;= 0.3010 + 0.3 \times 0.1761 + \frac{0.3(0.3-1)}{2!} (-0.0511) \\ \\
\implies P_2(2.3) &amp;= 0.3592
\end{aligned}
\]</span></p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Polinomio interpolante de grado 2 que pasa por los primeros 3 ptos</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>poli_g2 <span class="op">=</span> npol.Polynomial(npol.polyfit(x[:<span class="dv">3</span>], fx[:<span class="dv">3</span>], deg <span class="op">=</span> <span class="dv">2</span>))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la expresion del polinomio</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poli_g2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-0.2045 + 0.30385·x - 0.02555·x²</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluar el polinomio interpolante en el punto 2.3</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>poli_g2(<span class="fl">2.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.35919549999999956</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficarlo</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>y_g2 <span class="op">=</span> poli_g2(rango_x)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(datos[<span class="st">'x'</span>], datos[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'red'</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>plt.xlim(<span class="op">-</span><span class="fl">0.2</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(-0.2, 8.0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>plt.plot(rango_x, y_g2, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Polinomio interpolante de grado 2 con x0 = 2"</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(<span class="fl">2.3</span>, poli_g2(<span class="fl">2.3</span>), color <span class="op">=</span> <span class="st">"orange"</span>, s <span class="op">=</span> <span class="dv">100</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>plt.axvline(x<span class="op">=</span><span class="fl">2.3</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-24-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p><strong>Observación</strong>: es claro que no podemos esperar que este polinomio provea aproximaciones razonables para <span class="math inline">\(x\)</span> cercano al final del rango.</p></li>
<li><p>Lo bueno de este método, a diferencia del del Lagrange y al igual que la fórmula general, es que permite empezar por una interpolación de grado 1 e ir generado las aproximaciones de grado superior al agregar de a uno los términos siguientes, aprovechando los cálculos anteriores:</p></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Grado</th>
<th style="text-align: center;"><span class="math inline">\(P_n(2.3) =\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(f(x_0) + s \Delta^1_0 = 0.3538\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(0.3538 + \frac{s(s-1)}{2!}\Delta^2_0 = 0.3592\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(0.3592 + \frac{s(s-1)(s-2)}{3!}\Delta^3_0 = 0.3606\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(0.3606 + \frac{s(s-1)(s-2)(s-3)}{4!}\Delta^4_0 = 0.3611\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;"><span class="math inline">\(0.3611 + \frac{s(s-1)(s-2)(s-3)(s-4)}{5!}\Delta^5_0 = 0.3613\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li>En Python:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> grado <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">6</span>):</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(newton_adelante(fx, s <span class="op">=</span> <span class="fl">0.3</span>, g <span class="op">=</span> grado))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.35383
0.3591955
0.360564
0.36107406375
0.36131479777500003</code></pre>
</div>
</div>
<ul>
<li>La primera aproximación es una interpolación lineal y pasa por los primeros dos puntos; la segunda es cuadrática y pasa por los primeros tres puntos, etc.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>(-0.2, 8.0)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(-0.05, 1.0)</code></pre>
</div>
<div class="cell-output-display">
<p><img src="06_aprox_polin_parte1_files/figure-html/unnamed-chunk-26-7.png" class="img-fluid" width="768"></p>
</div>
</div>
<ul>
<li>La función que generó la tabla de este ejemplo es el logaritmo en base 10, es decir, que el valor exacto es <span class="math inline">\(f(2.3) = log(2.3) = 0.3617\)</span>.</li>
<li>Con esta información, podemos calcular el Error Relativo que resulta de hacer las aproximaciones anteriores:</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Grado</th>
<th style="text-align: center;"><span class="math inline">\(P_n(2.3) =\)</span></th>
<th style="text-align: center;">ER</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.3538</td>
<td style="text-align: center;">0.0218</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.3592</td>
<td style="text-align: center;">0.0070</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.3606</td>
<td style="text-align: center;">0.0032</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.3611</td>
<td style="text-align: center;">0.0018</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.3613</td>
<td style="text-align: center;">0.0012</td>
</tr>
</tbody>
</table>
</section>
<section id="otras-fórmulas-de-interpolación-de-newton" class="level3" data-number="1.3.5">
<h3 data-number="1.3.5" class="anchored" data-anchor-id="otras-fórmulas-de-interpolación-de-newton"><span class="header-section-number">1.3.5</span> Otras fórmulas de interpolación de Newton</h3>
<ul>
<li><p>Así como dijimos que cualquier valor <span class="math inline">\(x\)</span> puede ser expresado como <span class="math inline">\(x = x_0 + sh\)</span>, también podemos decir que cualquier valor <span class="math inline">\(x\)</span> puede ser expresado como <span class="math inline">\(x = x_n +sh\)</span> con <span class="math inline">\(s\)</span> negativo y los nodos se pueden escribir como <span class="math inline">\(x_i = x_n - (n-i)h\)</span>.</p></li>
<li><p>Teniendo en cuenta esto y haciendo varios reemplazos y pasos, el polinomio <span class="math inline">\(\eqref{eq:eq2}\)</span> queda así:</p>
<p><span class="math display">\[
  \begin{aligned}
  P_n(x)
  &amp;= f(x_n) - (-s) \Delta^1_{n-1} + \frac{-s(-s-1)}{2!} \Delta^2_{n-2} - \frac{-s(-s-1)(-s-2)}{3!} \Delta^3_{n-3} + ...\\
  &amp;= \sum_{k=0}^n (-1)^k {-s \choose k} \Delta_{n-k}^k
  \end{aligned}
  \]</span></p></li>
<li><p>Esta es la <strong>fórmula de interpolación de Newton con diferencias hacia atrás</strong>, porque utiliza la última diagonal desde abajo a la izquierda hacia arriba a la derecha de la <strong>tabla de diferencias ordinarias</strong>.</p></li>
<li><p>Hay que observar que la fórmula empieza con el valor de <span class="math inline">\(f(x_n)\)</span> y luego continúa empleando la última diferencia de cada orden.</p></li>
<li><p>No realizaremos ejemplos con esta forma de interpolación.</p></li>
<li><p>Sin embargo, al tener dos fórmulas de diferencias ordinarias para hacer interpolaciones, cabe preguntarse: ¿en qué se diferencian? ¿Cuál usar?</p></li>
<li><p>Ambas fórmulas son expresiones diferentes del <strong>mismo polinomio de grado</strong> <span class="math inline">\(n\)</span>, por lo tanto, es lo mismo usar una u otra.</p></li>
<li><p>No obstante, sus resultados pueden diferir por causa de los <strong>errores de redondeo</strong> propios de la aritmética finita con la que se realizan los tantísimos cálculos que hay que hacer y que son distintos en una y otra fórmula.</p></li>
<li><p>Si tenemos que interpolar para un <span class="math inline">\(x\)</span> cercano al comienzo de la tabla (es decir, más bien cerca de <span class="math inline">\(x_0\)</span>), conviene utilizar la fórmula hacia adelante. La misma empieza usando <span class="math inline">\(f(x_0)\)</span>, y estando <span class="math inline">\(x\)</span> cerca de <span class="math inline">\(x_0\)</span>, es de esperar que <span class="math inline">\(f(x_0)\)</span> esté cerca de <span class="math inline">\(f(x)\)</span>, por lo cual es un buen punto de partida.</p></li>
<li><p>En cambio, si tenemos que interpolar para un <span class="math inline">\(x\)</span> cercano al final de la tabla, por la misma razón conviene utilizar la fórmula hacia atrás.</p></li>
<li><p><em>Atención</em>: si en lugar de usar las fórmulas completas, empleamos menos términos para interpolar con polinomios de menor grado (es decir, que pasen por algunos pero no todos los <span class="math inline">\(x_i\)</span>), entonces los polinomios que resulten de una u otra fórmula ya no serán equivalentes (porque la fórmula hacia adelante usará los primeros puntos tabulados, mientras que la fórmula hacia atrás usará los últimos).</p></li>
<li><p>¿Y si el valor de <span class="math inline">\(x\)</span> está más bien cerca de mitad de tabla?…</p></li>
<li><p>Las fórmulas de diferencias hacia adelante y hacia atrás de Newton no son adecuadas para aproximar <span class="math inline">\(f(x)\)</span> cuando <span class="math inline">\(x\)</span> se encuentra cerca del centro de la tabla.</p></li>
<li><p>Existen varias fórmulas de diferencias divididas para este caso, cada una más ventajosa que otras para distintas situaciones.</p></li>
<li><p>Estos métodos reciben el nombre de <strong>fórmulas de diferencias centradas</strong>.</p></li>
<li><p>Uno de ellos se conoce como <strong>fórmula de Stirling</strong>.</p></li>
<li><p>La fórmula considera que <span class="math inline">\(x_0\)</span> es el nodo central y entonces hay que “cambiarle el nombre” a los valores de la tabla de diferencias ordinarias (pero son los mismos):</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="Plots/U6/dif3bis.png" class="img-fluid" style="width:80.0%"></p>
</div>
</div>
<!-- Tabla en md 

|  $x$     |  $f(x)$     | Primeras diferencias    | Segundas diferencias    | Terceras diferencias    | Cuartas diferencias |
|:--------:|:-----------:|:-----------------------:|:-----------------------:|:-----------------------:|:-------------------:|
| $x_{-2}$ | $f(x_{-2})$ |                         |                         |                         |                     |
|          |             |     $\Delta^1_{-2}$     |                         |                         |                     |
| $x_{-1}$ | $f(x_{-1})$ |                         |     $\Delta^2_{-2}$     |                         |                     |
|          |             |     $\Delta^1_{-1}$     |                         |     $\Delta^3_{-2}$     |                     |
| $x_0$    | $f(x_0)$    |                         |     $\Delta^2_{-1}$     |                         |     $\Delta^4_{-2}$ |
|          |             |     $\Delta^1_{0}$      |                         |     $\Delta^3_{-1}$     |                     |
| $x_1$    | $f(x_1)$    |                         |     $\Delta^2_{0}$      |                         |                     |
|          |             |     $\Delta^1_{1}$      |                         |                         |                     |
| $x_2$    | $f(x_2)$    |                         |                         |                         |                     |
-->
<ul>
<li><p>El polinomio de Stirling usa las diferencias que están pintadas, pero no consideraremos su fórmula.</p></li>
<li><p>En resumen, la siguiente tabla de diferencias ordinarias tiene indicadas cuáles son las que se usan en un polinomio de interpolación con las fórmulas de diferencias hacia adelante, hacia atrás y centradas.</p></li>
<li><p>Si se construye un polinomio de grado <span class="math inline">\(n\)</span>, los tres polinomios son el mismo.</p></li>
<li><p>Dependiendo de dónde se encuentre el punto <span class="math inline">\(x\)</span> a interpolar, conviene usar una u otra para disminuir errores de redondeo.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="Plots/U6/dif4.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<!-- Tabla en md  

|  $x$     |  $f(x)$     | Primeras diferencias    | Segundas diferencias    | Terceras diferencias    | Cuartas diferencias |
|:--------:|:-----------:|:-----------------------:|:-----------------------:|:-----------------------:|:-------------------:|
| $x_{0}$  | $f(x_{0})$  |                         |                         |                         |                     |
|          |             |     $\Delta^1_{0}$      |                         |                         |                     |
| $x_{1}$  | $f(x_{1})$  |                         |     $\Delta^2_{0}$      |                         |                     |
|          |             |     $\Delta^1_{1}$      |                         |     $\Delta^3_{0}$      |                     |
| $x_2$    | $f(x_2)$    |                         |     $\Delta^2_{1}$      |                         |     $\Delta^4_{0}$  |
|          |             |     $\Delta^1_{2}$      |                         |     $\Delta^3_{1}$      |                     |
| $x_3$    | $f(x_3)$    |                         |     $\Delta^2_{2}$      |                         |                     |
|          |             |     $\Delta^1_{3}$      |                         |                         |                     |
| $x_4$    | $f(x_4)$    |                         |                         |                         |                     |
-->
</section>
</section>
<section id="observaciones-finales" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="observaciones-finales"><span class="header-section-number">1.4</span> Observaciones finales</h2>
<ul>
<li>Un polinomio de grado <span class="math inline">\(n\)</span> ajustado a <span class="math inline">\(n+1\)</span> puntos es único.</li>
<li>El polinomio de interpolación se puede expresar en varias formas distintas, pero todas son equivalentes por el punto anterior.</li>
<li>Si tenemos <span class="math inline">\(n+1\)</span> puntos podemos calcular <span class="math inline">\(n\)</span> columnas de diferencias hacia adelante.</li>
<li>Si la función <span class="math inline">\(f(x)\)</span> que dio lugar a la tabla es un polinomio de orden <span class="math inline">\(q\)</span>, entonces la columna para la diferencia de orden <span class="math inline">\(q\)</span> es constante y las siguientes columnas son todas nulas.</li>
<li>Por lo tanto, si en el proceso de obtención de las diferencias sucesivas de una función, las diferencias de orden <span class="math inline">\(q\)</span> se vuelven constantes (o aproximadamente constantes), sabemos que los datos provienen exactamente (o muy aproximadamente) de un polinomio de orden <span class="math inline">\(q\)</span>.</li>
<li>Errores de redondeo podrían hacer que a pesar de que los datos provengan de un polinomio, no encontremos diferencias constantes.</li>
<li>Si una función se aproxima mediante un polinomio de interpolación, no hay garantía de que dicho polinomio converja a la función exacta al aumentar el número de datos. En general, la interpolación mediante un polinomio de orden grande debe evitarse o utilizarse con precauciones extremas.</li>
<li>Eso se debe a que los polinomios de orden superior pueden oscilar erráticamente; es decir, una fluctuación menor sobre una pequeña parte del intervalo puede inducir fluctuaciones grandes sobre todo el rango (ver ejemplo en la figura 3.14).</li>
<li>Aunque no existe un criterio para determinar el orden óptimo del polinomio de interpolación, generalmente se recomienda utilizar uno con orden relativamente bajo en un pequeño rango de <span class="math inline">\(x\)</span>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link  aria-label=" prefacio"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Prefacio</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>